const fs = require("fs");
const path = require("path");

const template = (queries, mutations) => {
return `# DO NOT MODIFY, auto generated by graphql-split ${new Date()}
type Query {
${queries.map(q => `  ${q}`).join("\n")}
}
type Mutation {
${mutations.map(m => `  ${m}`).join("\n")}
}
schema {
  query: Query
  mutation: Mutation
}
`;
};

const filepath = process.argv[2];

const base = fs.readFileSync(filepath).toString("utf-8");

const queries = [];
const mutations = [];
const adminQueries = [];
const adminMutations = [];

let current = "init";
base.split("\n").forEach(line => {
    const normalized = line.replace(/^\s+/, ""); // 先頭の空白を削除
    if (normalized === "type Query {") {
        current = "query";
        return;
    }
    if (normalized === "type Mutation {") {
        current = "mutation";
        return;
    }
    if (normalized === "schema {") {
        current = "schema";
        return;
    }
    if (normalized === "}") {
        current = "end";
        return;
    }
    if (current === "query" || current === "mutation") {
        if (!normalized) {
            // 空行
            return;
        }
        if (normalized[0] === "#") {
            // コメント行
            return;
        }
        if (normalized.indexOf("admin") === 0) {
            if (current === "query") {
                adminQueries.push(normalized);
            } else {
                adminMutations.push(normalized);
            }
        } else {
            if (current === "query") {
                // 一部共通Query/Mutationがあるのでadminには全てpushする
                adminQueries.push(normalized);
                queries.push(normalized);
            } else {
                // 一部共通Query/Mutationがあるのでadminには全てpushする
                adminMutations.push(normalized);
                mutations.push(normalized);
            }
        }
    }
});

const indexAdminClient = template(adminQueries, adminMutations);
const indexClient = template(queries, mutations);

fs.writeFileSync(path.resolve(__dirname, "index-admin-client.graphql"), indexAdminClient);
console.log("index-admin-client.graphql was generated.");
fs.writeFileSync(path.resolve(__dirname, "index-client.graphql"), indexClient);
console.log("index-client.graphql was generated.");
